image: node:6.5.0

stages:
  - build
  - deploy

build:
  stage: build
  variables:
    API_GET_FACILITIES: "https://api.srct.gmu.edu/whatsopen/v2/facilities/"
  script:
  - npm install
  - CI=false API_GET_FACILITIES=$API_GET_FACILITIES npm run build
  artifacts:
    paths:
    - build

build_shopmason:
  stage: build
  variables:
    API_GET_FACILITIES: "https://api.srct.gmu.edu/whatsopen/v2/facilities/?facility_classifier=shopmason"
  script:
  - npm install
  - CI=false API_GET_FACILITIES=$API_GET_FACILITIES npm run build
  artifacts:
    paths:
    - build
  when: manual

deploy_staging:
  stage: deploy
  script: echo "Deploy bot awayyyyy"
  environment:
    name: staging
    url: https://whatsopen.gmu.io
  only:
    - development

deploy_production:
  stage: deploy
  script: echo "Deploy bot awayyyyy"
  environment:
    name: production
    url: https://whatsopen.gmu.edu
  when: manual
  only:
    - master

