image: node:6.5.0

build:
  stage: build
  variables:
    API_GET_FACILITIES: "https://api.srct.gmu.edu/whatsopen/v2/facilities/"
  script:
  - npm install -g yarn
  - >
    sed "s|^const API_GET_FACILITIES .*|const API_GET_FACILITIES = '$API_GET_FACILITIES';|" src/actions/api.js
  - yarn install
  - npm run build
  artifacts:
    paths:
    - build

