image: node:6.5.0

build:
  stage: build
  variables:
    HOMEPAGE: "https://cefaoycoympc.srct.gmu.edu/"
  script:
  - >
    node -e "require('fs').writeFileSync('./package.json', JSON.stringify(Object.assign(require('./package.json'), {'homepage': process.env.HOMEPAGE}), null, 2));"
  - npm install
  - CI=false npm run build
  artifacts:
    paths:
    - build

